Facebook_django_project/Facebook_django_project/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf import settings

from django.conf.urls.static import static



urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('core.urls')),

    path('user/', include('userauths.urls')),


]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Facebook_django_project/core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [

    path('', views.index, name='feed'),

    path('post/<slug:slug>/', views.post_detail, name='post-detail'),

    path('core/inbox/', views.inbox, name='inbox'),

    path('core/inbox/<username>/', views.inbox_detail, name='inbox_detail'),

    # Ajax url's

    path("create_post/", views.create_post, name="create_post"),

    path("like-post/", views.like_post, name="like-post"),

    path("comment-post/", views.comment_on_post, name="comment-post"),

    path("like-comment/", views.like_comment, name="like-comment"),

    path("reply-comment/", views.reply_comment, name="reply-comment"),

    path("delete-comment/", views.delete_comment, name="delete-comment"),

    path("delete-reply/", views.delete_reply, name="delete-reply"),

    path("add-friend/", views.add_friend, name="add-friend"),

    path("accept-friend-request/", views.accept_friend_request, name="accept-friend-request"),

    path("reject-friend-request/", views.reject_friend_request, name="reject-friend-request"),

    path("unfriend/", views.unfriend, name="unfriend"),

]

Facebook_django_project/userauths/urls.py
from django.urls import path

from userauths import views

app_name = 'userauths'

urlpatterns = [

    path('sign-up/', views.RegisterView, name='sign-up'),

    path('sign-in/', views.LoginView, name='sign-in'),

    path('sign-out/', views.LogoutView, name='sign-out'),

    path('my-profile/', views.my_profile, name='my-profile'),

    path('profile/<username>', views.friend_profile, name='profile'),

]

Facebook_django_project/userauths/models.py
import os

from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image
from shortuuid.django_fields import ShortUUIDField

from django.db.models.signals import post_save

from django.utils.text import slugify
import shortuuid
from PIL import Image


GENDER = (
    ('male', 'Male'),
    ('female', 'Female'),
)

RELATIONSHIP = (
    ('single', 'Single'),
    ('married', 'Married'),
)


def user_directory_path(instance, filename):

    ext = filename.split('.')[-1]

    filename = '%s.%s' % (instance.user.id, ext)

    return 'user_{0}/{1}'.format(instance.user.id, filename)

class User(AbstractUser):

    full_name = models.CharField(max_length=200)

    username = models.CharField(max_length=200)

    email = models.EmailField(unique=True)

    phone = models.CharField(max_length=200)

    gender = models.CharField(max_length=100, choices=GENDER, default='male')

    otp = models.CharField(max_length=10, null=True,blank=True)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['username']

    def __str__(self):

        return self.username



class Profile(models.Model):

    pid = ShortUUIDField(length=7, max_length=25,alphabet='abcdefghijklmnopqrstuvwxyz')

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    cover_image = models.ImageField(upload_to=user_directory_path,blank=True, null=True, default='cover.jpg')

    image = models.ImageField(upload_to=user_directory_path,blank=True, null=True, default='default.jpg')

    full_name = models.CharField(max_length=200, null=True, blank=True)

    phone = models.CharField(max_length=200, null=True, blank=True)

    gender = models.CharField(max_length=100, choices=GENDER, default='male')

    relationship = models.CharField(max_length=100, choices=RELATIONSHIP, default='single')

    bio = models.CharField(max_length=200, null=True, blank=True)

    about_me = models.TextField(null=True, blank=True)

    country = models.CharField(max_length=200, null=True, blank=True)

    state = models.CharField(max_length=200, null=True, blank=True)

    city = models.CharField(max_length=200, null=True, blank=True)

    address = models.CharField(max_length=200, null=True, blank=True)

    working_at = models.CharField(max_length=200, null=True, blank=True)

    instagram = models.CharField(max_length=200, null=True, blank=True)

    whatsapp = models.CharField(max_length=200, null=True, blank=True)

    verified = models.BooleanField(default=False)

    followers = models.ManyToManyField(User, blank=True, related_name='followers')

    following = models.ManyToManyField(User, blank=True, related_name='following')

    friends = models.ManyToManyField(User, blank=True,related_name='friends')

    blocked = models.ManyToManyField(User, blank=True,related_name='blocked')

    date = models.DateTimeField(auto_now_add=True)

    slug = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):

        return self.user.username

    def save(self, *args, **kwargs):
        if not self.slug:
            uuid_key = shortuuid.uuid()
            uniqeid = uuid_key[:2]
            self.slug = slugify(self.full_name) + '-' + str(uniqeid.lower())

        super(Profile, self).save(*args, **kwargs)

        if self.image:
            image = Image.open(self.image.path)
            if image.format != 'JPEG':
                image = image.convert('RGB')
            image.save(self.image.path, format='JPEG', quality=70, optimize=True)

        if self.cover_image:
            cover_image = Image.open(self.cover_image.path)
            if cover_image.format != 'JPEG':
                cover_image = cover_image.convert('RGB')
            cover_image.save(self.cover_image.path, format='JPEG', quality=70, optimize=True)


def create_user_profile(sender, instance, created, **kwargs):

    if created:

        Profile.objects.create(user=instance)



def save_user_profile(sender, instance, **kwargs):

    instance.profile.save()


post_save.connect(create_user_profile, sender=User)

post_save.connect(save_user_profile, sender=User)

Facebook_django_project/userauths/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm

from userauths.models import User

class UserRegisterForm(UserCreationForm):

    full_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Full name', 'class': '', 'id': ""}))

    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'User name', 'class': '', 'id': ""})
                               , max_length=100, required=True)

    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Mobile No', 'class': '', 'id': ""})
                            , max_length=100, required=True)

    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Email Address', 'class': '', 'id': ""})
                            , required=True)

    password1 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Password', 'id': ""}), required=True)

    password2 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Confirm Password', 'id': ""})
                                , required=True)

    class Meta:

        model = User

        fields = ('full_name', 'username', 'email', 'phone', 'gender', 'password1', 'password2')


    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():

            visible.field.widget.attrs['class'] = "with-border"

Facebook_django_project/userauths/views.py
from django.shortcuts import render, redirect

from core.models import Post, FriendRequest
from userauths.forms import UserRegisterForm
from django.contrib import messages

from django.contrib.auth import authenticate, login, logout
from userauths.models import Profile, User
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


def RegisterView(request):

    if request.user.is_authenticated:

        messages.warning(request, 'your already registered!')

        return redirect("core:feed")

    form = UserRegisterForm(request.POST or None)

    if form.is_valid():

        form.save()

        full_name = form.cleaned_data.get('full_name')

        phone = form.cleaned_data.get('phone')

        email = form.cleaned_data.get('email')

        password = form.cleaned_data.get('password1')

        user = authenticate(email=email, password=password)

        login(request, user)

        profile = Profile.objects.get(user=request.user)

        profile.full_name = full_name

        profile.phone = phone

        profile.save()

        messages.success(request, f'Hi{full_name}, your account was created successfully.')

        return redirect("core:feed")

    context = {

        'form':form
    }

    return render(request, 'userauths/sign-up.html', context=context)


def LoginView(request):

    if request.user.is_authenticated:

        messages.warning(request, 'your already Login!')

        return redirect("core:feed")


    if request.method == 'POST':

        email = request.POST.get('email')

        password = request.POST.get('password')

        try:

            user = User.objects.get(email=email)

            user = authenticate(request, email=email, password=password)

            if user is not None:

                login(request, user)

                messages.success(request, 'your are Logged In.')

                return redirect("core:feed")

            else:

                messages.warning(request, 'Username or Password does not exist!')

                return redirect("userauths:sign-up")

        except:

            messages.error(request, 'User does not exist!')

            return redirect("userauths:sign-up")

    return HttpResponseRedirect("/")



def LogoutView(request):

    logout(request)

    messages.success(request, 'your are Logged Out.')

    return redirect("userauths:sign-up")

@login_required
def my_profile(request):

    profile = request.user.profile

    posts = Post.objects.filter(active=True, user=request.user).order_by('-id')

    context = {
        "profile": profile,
        "posts": posts
    }

    return render(request, "userauths/my-profile.html", context=context)


@login_required
def friend_profile(request, username):

    profile = Profile.objects.get(user__username=username)

    if request.user.profile == profile:

        return redirect("userauths:my-profile")

    posts = Post.objects.filter(active=True, user=profile.user).order_by('-id')

    bool = False
    bool_friend = False

    sender = request.user
    receiver = profile.user

    try:

        friend_request = FriendRequest.objects.get(sender=sender, receiver=receiver)

        if friend_request:
            bool = True
        else:
            bool = False
    except:
        bool = False

    context = {
        "profile": profile,
        "posts": posts,
        "bool": bool,

    }

    return render(request, "userauths/friend-profile.html", context=context)

Facebook_django_project/templates/userauths/sign-up.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="assets/images/favicon.png" rel="icon" type="image/png">

    <!-- Basic Page Needs
        ================================================== -->
    <title>Socialite Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Socialite is - Professional A unique and beautiful collection of UI elements">

    <!-- icons
    ================================================== -->
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">

    <!-- CSS 
    ================================================== -->
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <style>
        body {
            background-color: #f0f2f5;
        }
    </style>

</head>

<body>


    <div class="lg:flex max-w-5xl min-h-screen mx-auto p-6 py-10">
        <div class="flex flex-col items-center lg: lg:flex-row lg:space-x-10">

            <div class="lg:mb-12 flex-1 lg:text-left text-center">
                <img src="{% static 'assets/images/logo.png' %}" alt="" class="lg:mx-0 lg:w-52 mx-auto w-40">
                <p class="font-medium lg:mx-0 md:text-2xl mt-6 mx-auto sm:w-3/4 text-xl"> Connect with friends and the world around you on Socialite.</p>
            </div>
            <div class="lg:mt-0 lg:w-96 md:w-1/2 sm:w-2/3 mt-10 w-full">
                
                {% if form.errors %}
                
                # Allert message in Login page above
                    <div id="alert-border-4" class="flex items-center p-4 mb-4 text-red-800 border-t-4 border-yellow-300bg-yellow-50 dark:text-yellow-300 dark:bg-gray-800 dark:border-yellow-800" role="alert">
                        <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20"><path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                            
                        </svg>
                        <div class="ms-3 text-sm font-medium">

                            {{  form.errors }}
                            
                        </div>
                        <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-yellow-50 text-yellow-500 rounded-lgfocus:ring-2 focus:ring-yellow-400 p-1.5 hover:bg-yellow-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-yellow-300 dark:hover:bg-gray-700" data-dismiss-target="#alert-border-4" aria-label="Close">
                            
                          <span class="sr-only">Dismiss</span>
                            
                          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                              
                          </svg>
                            
                        </button>
                        
                    </div> 
                
                {% endif %}
            
                {% if messages %}
                    
                    {% for message in messages %}
                        
                        <div id="alert-border-4" class="flex items-center p-4 mb-4 text-green-800 border-t-4 border-green-300 bg-yellow-50 dark:text-green-300 dark:bg-gray-800 dark:border-yellow-800" role="alert">
                            
                            <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20"><path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                
                            </svg>
                            
                            <div class="ms-3 text-sm font-medium">
    
                                {{  message }}
                                
                            </div>
                            
                            <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-yellow-50 text-yellow-500 rounded-lgfocus:ring-2 focus:ring-yellow-400 p-1.5 hover:bg-yellow-200 inline-flex items-center justify-centerh-8 w-8 dark:bg-gray-800 dark:text-yellow-300 dark:hover:bg-gray-700" data-dismiss-target="#alert-border-4" aria-label="Close">
                                
                              <span class="sr-only">Dismiss</span>
                                
                              <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                                  
                              </svg>
                                
                            </button>
                            
                        </div> 
                    
                    {% endfor %}
                    
                {% endif %}
            
                <form class="p-6 space-y-4 relative bg-white shadow-lg rounded-lg" method="POST" action="{% url 'userauths:sign-in' %}">
                    
                    {% csrf_token %}
                    
                    <input type="email" name="email" placeholder="Email or Phone Number" class="with-border">
                    
                    <input type="password" name="password" placeholder="Password" class="with-border">
                    
                    <button type="submit" class="bg-blue-600 font-semibold p-3 rounded-md text-center text-white w-full">
                        
                        Log In
                        
                    </button>
                    
                    
                    <a href="#" class="text-blue-500 text-center block"> Forgot Password? </a>
                    
                    <hr class="pb-3.5">
                    
                    <div class="flex">
                        
                        <a href="#register" type="button" class="bg-green-600 hover:bg-green-500 hover:text-whitefont-semibold py-3 px-5 rounded-md text-center text-white mx-auto" uk-toggle>
                            
                            Create New Account
                            
                        </a>
                        
                    </div>
                    
                </form>

                <div class="mt-8 text-center text-sm"> <a href="#" class="font-semibold hover:underline"> Create a Page </a> for a celebrity, band or business </div>
            </div>

        </div>
    </div>

    <!-- This is the modal -->
    <div id="register" uk-modal>
        <div class="uk-modal-dialog uk-modal-body rounded-xl shadow-2xl p-0 lg:w-5/12">
            <button class="uk-modal-close-default p-3 bg-gray-100 rounded-full m-3" type="button" uk-close></button>
            <div class="border-b px-7 py-5">
                <div class="lg:text-2xl text-xl font-semibold mb-1"> Sign Up</div>
                <div class="text-base text-gray-600"> It’s quick and easy.</div>
            </div>
            <form class="p-7 space-y-5" method="post">
                
                {% csrf_token %}
                
                <div class="grid lg:grid-cols-2 gap-5">
                    
                    {{ form.full_name }}
                    {{ form.username }}
                    
                </div>
                
                {{ form.email }}
                {{ form.password1 }}
                {{ form.password2 }}

                <div class="grid lg:grid-cols-2 gap-3">
                    <div>
                        <label class="mb-0"> Gender </label>
                        
                        {{ form.gender }}
                        
                    </div>
                    <div>
                        <label class="mb-2"> Phone: optional  </label>
                        {{ form.phone }}
                    </div>
                </div>
                <p class="text-xs text-gray-400 pt-3">By clicking Sign Up, you agree to our
                    <a href="#" class="text-blue-500">Terms</a>,
                    <a href="#">Data Policy</a> and
                    <a href="#">Cookies Policy</a>. You may receive SMS Notifications from us and can opt out any time.
                </p>
                <div class="flex">
                    <button type="submit" class="bg-blue-600 font-semibold mx-auto px-10 py-3 rounded-md text-center text-white">
                        Get Started
                    </button>
                </div>
            </form>

        </div>
    </div>

    <!-- For Night mode -->
    <script>
        (function(window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' night-mode';
            }
        })(window, document);

        (function(window, document, undefined) {

            'use strict';

            // Feature test
            if (!('localStorage' in window)) return;

            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;

            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function(event) {
                event.preventDefault();
                document.documentElement.classList.toggle('dark');
                if (document.documentElement.classList.contains('dark')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);

        })(window, document);
    </script>

    <!-- Javascript
    ================================================== -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap-select.min.js' %}"></script>
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>

</body>

</html>